apiVersion: apps/v1


kind: Deployment


metadata:


  name: laravel-app-deployment


spec:


  replicas: 1


  selector:


    matchLabels:


      app: laravel-app


  template:


    metadata:


      labels:


        app: laravel-app


    spec:


      containers:


      - name: laravel-app-container


        image: titasuddin/laravel-app


        ports:


        - containerPort: 8090
