apiVersion: apps/v1


kind: Deployment


metadata:


  name: laravel-app:1.0.0-75


spec:


  replicas: 1


  selector:


    matchLabels:


      app: laravel-app:1.0.0-75


  template:


    metadata:


      labels:


        app: laravel-app:1.0.0-75


    spec:


      containers:


      - name: laravel-app:1.0.0-75


        image: titasuddin/laravel-app:1.0.0-75


        ports:


        - containerPort: 8081
