apiVersion: apps/v1


kind: Deployment


metadata:


  name: laravel-app:1.0.0-74


spec:


  replicas: 1


  selector:


    matchLabels:


      app: laravel-app:1.0.0-74


  template:


    metadata:


      labels:


        app: laravel-app:1.0.0-74


    spec:


      containers:


      - name: laravel-app:1.0.0-74


        image: titasuddin/laravel-app:1.0.0-74


        ports:


        - containerPort: 8081
