apiVersion: v1
kind: Service
metadata:
  name: laravel-app-service
  labels:
    app: laravel-app 
spec:
  selector:
    app: laravel-app

  ports:
    - port: 8080
      targetPort: 80

  type: LoadBalancer
